name: gvenzl oracle
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  odbTest:
    runs-on: ubuntu-latest

    services:
      odb3:
        image: gvenzl/oracle-xe:21-slim-faststart
        env:
          ORACLE_PASSWORD: 1.2.8MomOfferExpand 
        ports:
          - 1521:1521
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.14
    - name: Check for stdint.h
      run: |
        find /usr/include -name "stdint.h"
        echo "Using GCC version:"
        gcc --version
        echo "Using G++ version:"
        g++ --version
        echo | g++ -E -x c++ - -include cstdint | grep uint32_t
        echo | gcc -E -x c++ -v -
    - name: System Test
      run: tests/unittest3/testall.sh
